# Generated by Django 4.2.4 on 2023-08-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='converted_to_client',
            field=models.BooleanField(default=False, verbose_name='Convertir en client'),
        ),
    ]
