# Generated by Django 4.2.4 on 2023-08-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_record_converted_to_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='converted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date_conversion_en_client'),
        ),
    ]
